on: push
name: Build
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install Bazel
      run:  |
          sudo apt install curl gnupg software-properties-common
          sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
          curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update && sudo apt install bazel gcc-10 g++-10 lcov
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 40 --slave /usr/bin/g++ g++ /usr/bin/g++-10
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-10 40
          sudo update-alternatives --config gcc
          sudo update-alternatives --config gcov
    - name: Build
      run: bazel build -s //main:tgqif
    - name: Test
      run: bazel test $(bazel query //...)
    - name: Coverage
      run: |
        bazel coverage --combined_report=lcov $(bazel query 'tests(//...)')
        genhtml bazel-out/_coverage/_coverage_report.dat -o test_coverage
    - name: Save coverage
      uses: actions/upload-artifact@v2
      with:
        name: test_coverage
        path: test_coverage/**
